version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "database"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - comments_network
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "rest-api"
    ports:
      - "8080:8080"
    depends_on: 
      - db
    networks:
      - comments_network

volumes:
  database_postgres:

networks:
  comments_network:
    driver: bridge